In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3, 4]])
a.shape

(1, 4)

In [13]:
np.transpose(a)
a.shape

(1, 4)

In [17]:
np.random.rand((5,1))

TypeError: 'tuple' object cannot be interpreted as an integer

In [27]:
w = np.random.random((4,1))
w

array([[0.4503096 ],
       [0.10242804],
       [0.8576796 ],
       [0.79179928],
       [0.19249653]])

In [35]:
x = np.random.random((4,5))
x

array([[0.50913051, 0.87282498, 0.68686952, 0.55054913, 0.8108169 ],
       [0.21711843, 0.70533828, 0.18692039, 0.53101122, 0.3793459 ],
       [0.8798491 , 0.17547447, 0.45921515, 0.34105122, 0.70382682],
       [0.39430571, 0.85439604, 0.5195344 , 0.56880142, 0.70613525]])

In [45]:
w1 = np.transpose(w)
w1

array([[0.4503096 , 0.10242804, 0.8576796 , 0.79179928, 0.19249653]])

In [43]:
w1 * x

array([[0.22926635, 0.08940175, 0.58911398, 0.4359244 , 0.15607944],
       [0.09777051, 0.07224642, 0.16031781, 0.4204543 , 0.07302277],
       [0.39620449, 0.01797351, 0.39385947, 0.27004411, 0.13548422],
       [0.17755965, 0.08751411, 0.44559406, 0.45037655, 0.13592859]])